Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,61 +28,61 @@ jobs:
          restore-keys: | 
           ${{ runner.os }}-node-
         
-      - name: Install Snyk
-        run: npm install -g snyk
+      # - name: Install Snyk
+      #   run: npm install -g snyk
         
-      - name: Authenticate Snyk
-        run: snyk auth ${{ secrets.SNYK_TOKEN }}
+      # - name: Authenticate Snyk
+      #   run: snyk auth ${{ secrets.SNYK_TOKEN }}
 
-      - name: Test and Monitor Dependencies
-        run: snyk test
-        continue-on-error: true
-        
-      - name: Test and Monitor Dependencies
-        run: snyk test --json > snyk-report.json || true
-        
-      - name: Install snyk-to-html
-        run: npm install -g snyk-to-html
-        
-      - name: List contents of /home/runner/work
-        run: ls -la /home/runner/work/React_Todo/React_Todo
-        
-      - name: Convert JSON report to HTML
-        run: snyk-to-html -i snyk-report.json -o snyk-report.html
-        env:
-         PATH: React_Todo/React_Todo/snyk-report.json
-
-
-
-      - name: Upload HTML report
-        uses: actions/upload-artifact@v3
-        with:
-          name: snyk-report
-          path: snyk-report.html
-
-      - name: Fix vulnerabilities
-        run: npx snyk wizard --fail-on patchable
-
-      # - name: Run Snyk to check for vulnerabilities
-      #   uses: snyk/actions/node@master
+      # - name: Test and Monitor Dependencies
+      #   run: snyk test
       #   continue-on-error: true
-      #   env:
-      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-      #   with:
-      #     command: code test
-      #     args: --sarif-file-output=snyk.sarif
-
-      # - name: List directory contents
-      #   run: ls -la
-
-      # - name: Upload SARIF file
-      #   uses: github/codeql-action/upload-sarif@v3
-      #   with:
-      #     sarif_file: snyk.sarif
-      #     category: my-analysis-tool
         
-      # - name: Print Snyk report
-      #   run: cat snyk.sarif     
+      # - name: Test and Monitor Dependencies
+      #   run: snyk test --json > snyk-report.json || true
+        
+      # - name: Install snyk-to-html
+      #   run: npm install -g snyk-to-html
+        
+      # - name: List contents of /home/runner/work
+      #   run: ls -la /home/runner/work/React_Todo/React_Todo
+        
+      # - name: Convert JSON report to HTML
+      #   run: snyk-to-html -i snyk-report.json -o snyk-report.html
+      #   env:
+      #    PATH: React_Todo/React_Todo/snyk-report.json
+
+
+
+      # - name: Upload HTML report
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: snyk-report
+      #     path: snyk-report.html
+
+      # - name: Fix vulnerabilities
+      #   run: npx snyk wizard --fail-on patchable
+
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/node@master
+        continue-on-error: true
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        with:
+          command: code test
+          args: --sarif-file-output=snyk.sarif
+
+      - name: List directory contents
+        run: ls -la
+
+      - name: Upload SARIF file
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: snyk.sarif
+          category: my-analysis-tool
+        
+      - name: Print Snyk report
+        run: cat snyk.sarif     
 
       - name: Run Trivy vulnerability scanner in repo mode
         uses: aquasecurity/trivy-action@master
